name:  Feature Request
description: Prop贸n una nueva funcionalidad
title: "[FEATURE] - "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tu propuesta   
        Ay煤danos con la siguiente informaci贸n.

  - type: textarea
    id: problema
    attributes:
      label:  Problema que resuelve
      description: 驴Qu茅 problema actual resuelve esta feature?
    validations:
      required: true

  - type: textarea
    id: solucion
    attributes:
      label:  Soluci贸n propuesta
      description: Describe tu idea claramente.
    validations:
      required: true

  - type: textarea
    id: alternativas
    attributes:
      label:  Alternativas consideradas
      description: 驴Has considerado otras soluciones?

  - type: textarea
    id: contexto
    attributes:
      label:  Contexto adicional
      description: Cualquier informaci贸n relevante.